joy:
  ros__parameters:
    # device_name: /dev/input/joypad-f710
    device_id: 0
    deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval: 0.01

joy_teleop:
  ros__parameters:
    default:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 0.0
          offset: 0.0
        drive-steering_angle:
          axis: 2
          scale: 0.0
          offset: 0.0

    human_control_forward_slow:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [4]
      axis_mappings:
        drive-speed:
          axis: 5
          scale: -1.0
          offset: 1.0
        drive-steering_angle:
          axis: 0
          scale: 0.28
          offset: 0.0304

    human_control_reverse_slow:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [5]
      axis_mappings:
        drive-speed:
          axis: 2
          scale:   1.0
          offset: -1.0
        drive-steering_angle:
          axis: 0
          scale: 0.28
          offset: 0.0304

    human_control_forward_sicko_mode:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [0]
      axis_mappings:
        drive-speed:
          axis: 5
          scale: -2.25
          offset: 2.25
        drive-steering_angle:
          axis: 0
          scale: 0.28
          offset: 0.0304

    human_control_reverse_sicko_mode:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [1]
      axis_mappings:
        drive-speed:
          axis: 2
          scale:   2.25
          offset: -2.25
        drive-steering_angle:
          axis: 0
          scale: 0.28
          offset: 0.0304

    autonomous_control:
      type: topic
      interface_type: std_msgs/msg/Int8
      topic_name: /dev/null
      deadman_buttons: [3]
      message_value:
        data:
          value: 0
