ackermann_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : safe_drive
        timeout : 0.2
        priority: 100
      joystick:
        topic   : teleop
        timeout : 0.2
        priority: 10
